vich_uploader:
  db_driver: orm
  mappings:
    media_object:
      delete_on_remove: true
      delete_on_update: true
      inject_on_load: true
      uri_prefix: /media
      upload_destination: "%kernel.project_dir%/public/media"
      # directory_namer: app_service.directory_namer
      # Will rename uploaded files using a uniqueid as a prefix.
      namer: Vich\UploaderBundle\Naming\OrignameNamer
  #mappings:
  #    products:
  #        uri_prefix: /images/products
  #        upload_destination: '%kernel.project_dir%/public/images/products'
